name: "Automate-Terra-Azure"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Azure Credentials
        uses: actions/cache@v2
        with:
          path: ~/.azure
          key: ${{ runner.os }}-azure-credentials-${{ hashFiles('**/.azure/**') }}
          restore-keys: |
            ${{ runner.os }}-azure-credentials-

      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Set Azure Subscription
        if: steps.cache.outputs.cache-hit != 'true'
        run: az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Debug Azure Subscription ID
        run: az account show

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan

      - name: Terraform Apply
        id: Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve

        
